### ISSUE TITLE
NetworkLayer Implementation

### ISSUE THREAD

**Issue by 3zcurdia** [iOSLabUNAM/Diplomado7G#11]
Implement a project where you make a request call to the rick and Morty api and Redner all characters on a table view

- Continue the class work by implementing pagination

## Bonus

- Implement an infinity scroll 

## Evaluacion
  🎉 = 10
  👍 = 9
  😄 = 8

**Comment by retroskateboard** [comment]
Rojas Pech Eric - https://github.com/retroskateboard/RickAndMorthy

**Comment by ericmargay** [comment]
Eric Margay - https://github.com/ericmargay/RickandMorty.git

**Comment by CesarGOC** [comment]
César Alejandro Guadarrama Ortega - https://github.com/CesarGOC/DiplomadoModulo5

**Comment by carlos2297** [comment]
Rangel Garcia Carlos Alberto - https://github.com/carlos2297/diplomado-iOS/tree/main/RickAndMorty

**Comment by LFernandoGO** [comment]
Gutierrez Orozpe Luis Fernando - https://github.com/LFernandoGO/RickAndMortyAPI

**Comment by CristianRomeroG10** [comment]
Romero Garcia Cristian Guillermo - https://github.com/CristianRomeroG10/RickAndMorty

**Comment by ricardo-casa** [comment]
Ricardo Carrillo Sanchez - https://github.com/ricardo-casa/Rick-MortyAPI

**Comment by Brann7** [comment]
Brandon Luna Pérez: https://github.com/Brann7/diplomado-ios/tree/738a9aad10809343efbf36cb8e7eeb17d2a7c4ef/RickAndMorty

**Comment by FernandoMeza99** [comment]
Meza Argüello Luis Fernando https://github.com/FernandoMeza99/Modulo5.git

**Comment by PaulafloresS** [comment]
https://github.com/PaulafloresS/DiploQuintoModulo.git

**Comment by LuisMPS** [comment]
Perez Saldaña Luis Mario https://github.com/LuisMPS/RickAndMorty

**Comment by SoubranMx** [comment]
Uriel Alejandro Estrada Soubran - https://github.com/SoubranMx/iOS2024-RickAndMortyAPI con infinite scroll, swift ui.

**Comment by shenshuais** [comment]
Shuai Shen - https://github.com/shenshuais/RickandMorty.git

**Comment by AlanSerralde** [comment]
Alan Serralde - https://github.com/AlanSerralde/RickAndMorty

**Comment by Amanda1003** [comment]
Amanda Aguilar: https://github.com/Amanda1003/DiplomadoDesarrollo-iOS/blob/7db895455a344b7365dd295669902b4b025dbd2c/SwiftUIBasics.xcodeproj.zip

**Comment by JesusJaime9** [comment]
Jesús Jaime García https://github.com/JesusJaime9/RickyMorty.git

**Comment by Yael1427** [comment]
Puente López Gandhi Yael - https://github.com/Yael1427/RickAndMorty

**Comment by Alsxilva** [comment]
Alejandro Silva Guzmán - https://github.com/Alsxilva/RickAndMorty.git

**Comment by Danielmr97** [comment]
Jesus Daniel Mayo Ruiz
[https://github.com/Danielmr97/RickAndMorthy](url)

**Comment by romystark** [comment]
Román Santiago Anaya - https://github.com/romystark/Rickmorty.git

**Comment by eduardoquintero117** [comment]
Eduardo Quintero Juan - [https://github.com/eduardoquintero117/DiplomadoModulo5](url)

**Comment by Ramon-OC** [comment]
Ortiz Castañeda José Ramón - https://github.com/Ramon-OC/Diplomado7G/tree/main

**Comment by teredl8** [comment]
Teresita de Jesús Durán López - https://github.com/teredl8/RickAndMorty.git
