### ISSUE TITLE
Interview simulation

### ISSUE THREAD

**Issue by 3zcurdia** [iOSLabUNAM/Diplomado7G#12]
The instructor will act as a technical interviewer and asses and evaluate each candidate .

To be interviewed it will require the following data in a comment:
- Name
- Years of experience
- Education (degree and school)
- Public profile (GitHub, linkedin, website) or CV
- Relevant experience (optional)

**Comment by FernandoMeza99** [comment]
Luis Fernando Meza Argüello
1 year 7 months
Bachelor's Degree in Computer Engineering 

[FernandoMeza_CV_english.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928839/FernandoMeza_CV_english.pdf)

Relevant Experience: JavaScript, React, Next JS.

**Comment by AliHCS** [comment]
Gustavo Ali Gómez Trejo
2 Years 1 month
Bachelor's Degree in Computer Engineering

[Curriculum 2023 sin foto.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928847/Curriculum.2023.sin.foto.pdf)

Relevant Experience: JavaScript, Typescript, VueJs, NodeJs, MogoDB.

**Comment by CristianRomeroG10** [comment]
Name: Romero Garcia Cristian Guillermo
Years of experience: 1 Year 4 month
Education: Bachelor´s Degree in Mechatronic Engineering
[RomeroGarciaCristianGuillermo_Currriculum-2.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928853/RomeroGarciaCristianGuillermo_Currriculum-2.pdf)
Relevant experience: Swift, UIKit

**Comment by shenshuais** [comment]
Name: Shuai Shen
Years of experience: 1 year as a specialist in Uber and 6 Months as a Python developer. 
Education: bachelor's degree in computer engineering 
CV: [ShuaiShen_resume.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928858/ShuaiShen_resume.pdf)
Relevant Experience: Python, ML models, and SQL

**Comment by Brann7** [comment]
Brandon Luna Pérez
1 year of experience
Bachelor degree on Computer
[CV BRANDON lUNA PÉREZ.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928872/CV.BRANDON.lUNA.PEREZ.pdf)
Relevant Experience: Java, Swift, PHP

**Comment by retroskateboard** [comment]
- Rojas Pech Eric 
- 1 year
- Bachelor's degree in Computer Engineering
- [Linkedin](https://www.linkedin.com/in/eric-rojas-pech-35b9a9226/)
- [Github](https://www.github.com/retroskateboard )
- Intern at BBVA México, in the area of finance, i made majors in the data bases to have accessibility 24/7, resumes of data for clients. 
- Software Associate Solutions Development II in BBVA México 💙 as help area.

**Comment by PaulafloresS** [comment]
Ana Paula Flores Salinas 
2 year of experience 
Bachelor's Degree in computer Engineering 
[Linkedin](www.linkedin.com/in/ana-paula-flores-salinas)
[Github](https://github.com/PaulafloresS)
[CV_FloresSalinasAnaPaula.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928867/CV_FloresSalinasAnaPaula.pdf)
Relevant Experience : Swift, Android , Java , Python, SQL

**Comment by LFernandoGO** [comment]
Luis Fernando Gutierrez Orozpe
Year and a half of experience
Bachelor degree on Computer Engineering at School of Engineering of the National Autonomous University of Mexico
[Curriculum.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928846/Curriculum.pdf)
Relevant Experience: I developed and designed by myself an app that make a consult of the NASA API with the objective to show to the users the Astronomic Picture Of the Day. In this project, I implemented a third-party dependency called "SkelletonView" that is used to animate the elements of the view until the data is loaded.

**Comment by Amanda1003** [comment]
Name: Amanda Aguilar
Years of experience: 2 años como asistente de profesor de física computacional (Python)
Education (degree and school): Física (grado de licenciatura)
Public profile (GitHub, linkedin, website) or CV: https://www.linkedin.com/in/amanda-a-6b533b27a/
https://docs.google.com/document/d/1reAQ3sEu-tCXChW65zYCAbDgpnnqxtvRDZYtu51AJiI/edit?usp=sharing
Relevant experience (optional): Una certificación en computación cuántica.

**Comment by ricardo-casa** [comment]
Ricardo Carrillo
years of experience: 1 year 
education: bachelor degree in computer engineering
my github: https://github.com/ricardo-casa

**Comment by Danielmr97** [comment]
Jesus Daniel Mayo Ruiz
Years of experence : 1 year 9 month
Bachelor's Degree in Computer Engineering
CV:  [MayoRuizJesusDaniel.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928870/MayoRuizJesusDaniel.pdf)
Relevan experence : In bbva I am in charge of the creation of a parallel flow where this flow is activated by an openweb flag which is activated when the service is down, in this flow protocols were implemented, collectionviews, tableviews, etc. change of core flows of the application because it had limited resources, also a remapping and change of the endpoint was made, for the consumption of the service, finally I was in charge of the implementation of this flow worldwide making the necessary pull request.

**Comment by ericmargay** [comment]
Name: Eric Margay
Years of experience: 1 year and 8 months as a Python developer.
Education: Bachelor's degree in Technology.
CV: https://ericmargay.github.io/ResumeCV/
https://www.linkedin.com/in/ericmargay/
Relevant Experience: Software Developer Tools in Ford, Hardware Experience in Tech and Art.

**Comment by eduardoquintero117** [comment]
Eduardo Quintero Juan
1 Years of experience
Bachelor's Degree in Electrical Electronic Engineering
CV : [Eduardo_Quintero_CV_English_iOS_DeveloperV1.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13928959/Eduardo_Quintero_CV_English_iOS_DeveloperV1.pdf)
linkedin : https://www.linkedin.com/in/eduardo-quintero-juan-b1a09923a
I built an app that won a contest

**Comment by SoubranMx** [comment]
Uriel Alejandro Estrada Soubran
2 years and 7 months of experience
Bachelor's Degree in Computer Engineering
CV: 
[CV_UrielSoubran.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13929152/CV_UrielSoubran.pdf)
LinkedIn: [Uriel Soubran](https://www.linkedin.com/in/uriel-soubran/)
Relevant experience: I have worked in one of the most big tech companies, Accenture, for over a year in web development, leading to meet diverse teammates, talking in English on daily meeting standups, showcasing work for clients every end of sprint, working and helping my team's members, etc. I am now learning Angular in order to improve further my career.
Skills in javascript, React, NextJS, Jest/RTL, e-Commerce development.

**Comment by teredl8** [comment]
Tere Durán López
1 year of experience
Bachelor's degree in Computer Engineering
[Tere Durán López CV.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13929181/Tere.Duran.Lopez.CV.pdf)
Relevant experience: Swift

**Comment by AlanSerralde** [comment]
Name: Alan Serralde Contreras

Years of experience: 1 año de servicio social dando clases propedéuticas a los jóvenes que esperaban ingresar a la facultad de ciencias.

Education (degree and school): Egresado de matemáticas

Public profile (GitHub, linkedin, website) or CV: 

![Alan Serralde Contreras CV pdf_1-3](https://github.com/iOSLabUNAM/Diplomado7G/assets/142637553/c6c161ca-98e6-48b5-ab7e-86cfb9f5954f)

Relevant experience (optional): Realice una app de asistencia para sordos

**Comment by Alsxilva** [comment]
Name: Alejandro Silva Guzmán

Years of experience: a year inside Biorobotic's Lab, Faculty of Engineering, UNAM

Education (degree and school): Computer Engineering

Public profile (GitHub, linkedin, website) or CV:

www.linkedin.com/in/alsxilva
https://github.com/Alsxilva

[Alejandro Silva - CV.pdf](https://github.com/iOSLabUNAM/Diplomado7G/files/13929280/Alejandro.Silva.-.CV.pdf)

Relevant experience: Ayudante de profesor, 1 año en maestría en Procesamiento Digital de Señales.

**Comment by Ramon-OC** [comment]
Name: Ortiz Castañeda José Ramón
No experience yet
Education: Bachelor´s Degree in Computer Science 
[CV-2023.pdf](https://drive.google.com/file/d/1xSsQrnhvlKp5ijsY9mgzjFBCwdV1wBbB/view?usp=share_link)
Relevant experience: Image Processing, Haskell, MATLAB, Java and Swift
