### ISSUE TITLE
Modulo 4: Kits & 3rd party devs

### ISSUE THREAD

**Issue by 3zcurdia** [iOSLabUNAM/Diplomado7G#4]
## Temario

- [x] CoreLocation
- [x] MapKit
- [x] Camera
- [x] Photo Library
- [x] Biometrics (FaceID)
- [x] Animations
- [x] SpriteKit
- [x] Swift Package Manager

**Comment by zippi-MD** [comment]
También pudimos ver una breve introducción a:
- Retención de memoria - vimos un ejemplo de la importancia de usar `weak` en los delegados y como identificar un ciclo de retención de memoria
- Grand Central Dispatch - cargamos una imagen de internet y también lo utilizamos para mostrar una ruta en el mapa, mencionamos que cambios en la UI tienen que ejecutarse en el hilo principal
